#端口
server:
  port: 8080
  servlet:
    context-path: /
# 打印sql
logging:
  level:
     com.yaspeed.web.mapper : debug
#热部署关闭false
spring:
  devtools:
     restart:
        enabled: false
  activemq:
    broker-url: tcp://localhost:61616
